posts/routes.py
import pymysql
from db_config import mysql
from flask import Blueprint,url_for
from flask import flash, render_template, request, redirect, session

posts = Blueprint('posts',__name__,template_folder='templates')

@posts.route("/new")
def create_post():
    if session['loggedin']:
        return render_template("posts/create_post.html")
    else:
        return render_template('auth/login.html',error="Login to proceed")



@posts.route("/post", methods=["POST"])
def post():
    conn = None
    cursor = None
    try:
        _title = request.form["title"]
        _content = request.form["content"]
        if _title and _content and request.method == "POST":
            sql = "INSERT INTO posts(title,content,user_id) VALUES (%s, %s, %s)"
            data = (_title, _content, session['id'])
            conn = mysql.connect()
            cursor = conn.cursor()
            cursor.execute(sql, data)
            conn.commit()
            flash("Post added successfully!!")
            return redirect("/")
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

@posts.route("/post_comment/<int:post_id>", methods=["POST"])
def post_comment(post_id):
    conn = None
    cursor = None
    try:
        _name = request.form["name"]
        _comment = request.form["comment"]
        if _name and _comment and request.method == "POST":
            sql = "INSERT INTO comments(name,comment,post_id,user_id) VALUES (%s, %s, %s, %s)"
            data = (_name, _comment, post_id, session['id'])
            conn = mysql.connect()
            cursor = conn.cursor()
            cursor.execute(sql, data)
            conn.commit()
            return redirect(url_for('posts.show',id=post_id))
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()


@posts.route('/show/<int:id>')
def show(id):
    conn = None
    cursor = None
    try:
        sql = "SELECT * FROM posts WHERE id = %s"
        data = (id)
        conn = mysql.connect()
        cursor = conn.cursor()
        cursor.execute(sql, data)
        post = cursor.fetchone()
        sql = "SELECT * FROM users WHERE ID IN ( SELECT user_id FROM posts WHERE id = %s)"
        cursor.execute(sql,data)
        user = cursor.fetchone()
        sql = "SELECT * FROM comments where post_id = %s"
        cursor.execute(sql,data)
        comments = cursor.fetchall()
        return render_template('posts/show_post.html',post = post,comments = comments, user = user)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()

@posts.route('/delete_comment/<int:post_id>/<int:comment_id>')
def delete_comment(post_id,comment_id):
    conn = None
    cursor = None
    try:
        sql = "DELETE FROM comments where id = %s"
        data = (comment_id)
        conn = mysql.connect()
        cursor = conn.cursor()
        cursor.execute(sql, data)
        conn.commit()
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()
    return redirect(url_for('posts.show',id=post_id))
    
    
@posts.route('/edit_post/<int:id>')
def edit_post(id):
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT * FROM posts WHERE id = %s",id)
        row = cursor.fetchone()
        if row:
            return render_template('posts/edit_post.html',row=row)
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()            

@posts.route('/delete_post/<int:id>')
def delete_post(id):
    conn = None
    cursor = None
    try:
        conn = mysql.connect()
        cursor = conn.cursor()
        sql = "DELETE FROM comments where post_id = %s"
        data = (id)
        cursor.execute(sql,data)
        conn.commit()
        sql = "DELETE FROM posts where id = %s"
        cursor.execute(sql,data)
        conn.commit()
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()
    return redirect(url_for('main.index'))

@posts.route('/update_post/<int:id>',methods=['POST'])
def update_post(id):
    conn = None
    cursor = None
    try:
        _title = request.form['title']
        _content = request.form['content']
        if _title and _content and request.method == 'POST':
            sql = "UPDATE posts SET title = %s, content = %s where id = %s"
            data = (_title,_content,id)
            conn = mysql.connect()
            cursor = conn.cursor()
            cursor.execute(sql,data)
            conn.commit()
            return redirect(url_for('posts.show',id=id))
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close() 

posts/templates/posts/create_post.html
{% extends "base.html"%}
{% block content%}
<div class="container">
    <div class="post-div">
        <h4 align="center">Create New Post</h4>
        <form action="/post" method="post">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Title ...">
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea name="content" class="form-control" id="content" rows="5"
                    placeholder="Content here ....."></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="create post" class="btn btn-primary sub">
            </div>
        </form>
    </div>

</div>

{% endblock content%}

posts/templates/posts/edit_post.html
{% extends "base.html"%}
{% block content%}
<div class="container">
    <div class="post-div">
        <h4 align="center">Edit Post</h4>
        <form action="{{url_for('update_post',id=row['id'])}}" method="post">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" value="{{row.title}}" name="title" id="title"
                    placeholder="Title ...">
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea name="content" class="form-control" id="content" rows="5"
                    placeholder="Content here .....">{{row.content}}</textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="update post" class="btn btn-primary sub">
            </div>
        </form>
    </div>

</div>

{% endblock content%}

posts/templates/posts/show_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="post-head">
        <h1>{{post[1]}}</h1>
    </div>
    <div class="post-body">
        <p class="drop-cap">{{post[2]}}</p>
    </div>
    <div class="whome">
        <div class='at'><span class="post-a">Posted at:: <strong>{{post[4]}}</strong></span></div>
        <div class='by'><span class="post-b">By:: <strong>{{user[1].split('@')[0]}}</strong></span></div>
    </div>
    <hr>
    {% if session['loggedin']%}
    {% if session['id'] == post[3] %}
    <div class="actions">
        <div class="action-head">
            <h5>Actions</h5>
        </div>
        <div class="action-buttons">
            <a href="{{url_for('posts.edit_post',id=post[0])}}">
                <button type="button" class="btn btn-info btn-sm">Edit</button>
            </a>
            <a href="{{url_for('posts.delete_post',id=post[0])}}">
                <button type="button" class="btn btn-danger btn-sm"
                    onclick="return confirm('Are you sure ?')">Delete</button>
            </a>
        </div>
    </div>
    {% endif %}
    {% endif %}
    <div class="comments">
        <h4>Comments</h4>
        <hr>
        {% if comments|count > 0 %}
        {% for comment in comments %}
        <div class="comment-row">
            <div class="comment">
                <h5><strong>{{comment[1]}}::&nbsp;&nbsp;</strong>{{comment[2]}}</h5>
            </div>
            {% if session['loggedin']%}
            {%if comment[4] == session['id']%}
            <div class="del">
                <a href="{{url_for('posts.delete_comment',post_id=comment[3],comment_id=comment[0])}}">
                    <button type="button" class="btn btn-danger btn-sm"
                        onclick=" return confirm('Are you sure ?')">Delete</button>
                </a>
            </div>
            {%endif%}
            {%endif%}
        </div>
        {% endfor %}
        {% else %}
        <h6>No Comments Yet :(</h6>
        {% endif %}
        <hr>
    </div>
    <div class="comments-form">
        <h5>Leave a comment</h5>
        <hr>
        {%if session['loggedin']%}
        <form action="{{url_for('posts.post_comment',post_id=post[0])}}" method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Name ..."
                    value={{session['uname'].split('@')[0]}}>
            </div>
            <div class=" form-group">
                <label for="comment">Comment</label>
                <input type="text" class="form-control" name="comment" id="comment" placeholder="Comment ...">
            </div>
            <div class="form-group">
                <input type="submit" value="Post Comment" class="btn btn-primary sub">
            </div>
        </form>
        {%else%}
        <h6>Login to leave a comment</h6>
        {%endif%}
    </div>
</div>
{% endblock content%}